backend:
  name: git-gateway
  branch: main

media_folder: "src/content/uploads"        # Where uploaded images will be stored in your repo
public_folder: "/src/content/uploads"      # How those images will be accessed on the front-end

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "teams"
    label: "People"
    folder: "src/content/teams"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Profession", name: "profession", widget: "string" }
      - { label: "Institution", name: "institution", widget: "string" }
      - { label: "Expertise", name: "expertise", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "LinkedIn", name: "linkedin", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "articles"
    label: "Publications"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Image Alt", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
